In [64]:
import numpy as np
import pandas as pd

In [65]:
df = pd.read_csv('customer.csv')


In [66]:
df.sample(5)


age  gender review education purchased
40   39    Male   Good    School        No
2    70  Female   Good        PG        No
1    68  Female   Poor        UG        No
48   39  Female   Good        UG       Yes
38   45  Female   Good    School        No

In [67]:
df = df.iloc[:,2:]

In [68]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [69]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [75]:
X_train

review education
3      Good        PG
43     Poor        PG
9      Good        UG
14     Poor        PG
41     Good        PG
24  Average        PG
23     Good    School
31     Poor    School
38     Good    School
2      Good        PG
48     Good        UG
21  Average        PG
7      Poor    School
40     Good    School
13  Average    School
19     Poor        PG
8   Average        UG
16     Poor        UG
36     Good        UG
20  Average    School
15     Poor        UG
22     Poor        PG
45     Poor        PG
4   Average        UG
34  Average    School
29  Average        UG
5   Average    School
1      Poor        UG
44  Average        UG
42     Good        PG
12     Poor    School
33     Good        PG
26     Poor        PG
35     Poor    School
37  Average        PG
27     Poor        PG
11     Good        UG
32  Average        UG
30  Average        UG
39     Poor        PG

In [76]:
from sklearn.preprocessing import OrdinalEncoder

In [77]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])


In [78]:
oe.fit(X_train)


OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [79]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [80]:
X_train


array([[2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [0., 2.]])

In [81]:
oe.categories_


[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [82]:
X_train


array([[2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [0., 2.]])

In [83]:
from sklearn.preprocessing import LabelEncoder # LebelEncoding is only used for the output column

In [84]:
le = LabelEncoder()


In [85]:
le.fit(y_train)


LabelEncoder()

In [86]:
le.classes_


array(['No', 'Yes'], dtype=object)

In [87]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)


In [88]:
y_train


array([0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0])